"""Assemble a self-describing, offline DOI package from canonical metadata.

Layout produced (matches the spec):

    <outdir>/
        <artifact files...>          (copied in)
        <artifact>.sha256            (one per file)
        metadata.json                (canonical Misty record)
        zenodo.json                  (Zenodo deposit body)
        datacite.json                (DataCite 4.x)
        codemeta.json                (schema.org SoftwareSourceCode)
        CITATION.cff                 (CFF 1.2.0)
        manifest.json                (release + reproducibility manifest)
        README.md                    (human summary of the package)

The package is fully reproducible and contains no secrets, so it is safe to
commit, attach to a GitHub release, or hand to an air-gapped reviewer.
"""

from __future__ import annotations

import json
import os
import shutil
from typing import Any, Dict, List, Optional

from . import checksum, transform


def build_metadata_files(m: Dict[str, Any], outdir: str) -> List[str]:
    """Write zenodo/datacite/codemeta/CFF + canonical metadata.json."""
    os.makedirs(outdir, exist_ok=True)
    written: List[str] = []

    canonical = os.path.join(outdir, "metadata.json")
    with open(canonical, "w", encoding="utf-8") as fh:
        json.dump(m, fh, indent=2, ensure_ascii=False)
    written.append(canonical)

    for filename, (fn, is_json) in transform.TARGETS.items():
        dest = os.path.join(outdir, filename)
        payload = fn(m)
        with open(dest, "w", encoding="utf-8") as fh:
            if is_json:
                json.dump(payload, fh, indent=2, ensure_ascii=False)
            else:
                fh.write(payload + "\n")
        written.append(dest)
    return written


def build_package(
    m: Dict[str, Any],
    files: List[str],
    outdir: str,
    *,
    doi: Optional[str] = None,
) -> Dict[str, Any]:
    """Build the full doi-package directory. Returns the manifest dict."""
    os.makedirs(outdir, exist_ok=True)

    file_records: List[Dict[str, Any]] = []
    for src in files:
        if not os.path.isfile(src):
            raise FileNotFoundError(f"artifact not found: {src}")
        rec = checksum.file_record(src)
        dest = os.path.join(outdir, rec["name"])
        if os.path.abspath(src) != os.path.abspath(dest):
            shutil.copy2(src, dest)
        with open(dest + ".sha256", "w", encoding="utf-8") as fh:
            fh.write(f"{rec['sha256']}  {rec['name']}\n")
        file_records.append(rec)

    build_metadata_files(m, outdir)

    manifest = {
        "title": m["title"],
        "version": m.get("version"),
        "doi": doi or m.get("doi"),
        "license": m["license"],
        "artifacts": file_records,
        "metadata_files": [
            "metadata.json", "zenodo.json", "datacite.json",
            "codemeta.json", "CITATION.cff",
        ],
        "reproducibility": {
            "checksums": {r["name"]: r["sha256"] for r in file_records},
            "tool": "misty-doi",
        },
    }
    with open(os.path.join(outdir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)

    _write_readme(m, manifest, outdir)
    return manifest


def _write_readme(m: Dict[str, Any], manifest: Dict[str, Any], outdir: str) -> None:
    authors = ", ".join(c["name"] for c in m.get("creators", []))
    lines = [
        f"# {m['title']}",
        "",
        f"**Version:** {m.get('version', '')}  ",
        f"**Authors:** {authors}  ",
        f"**License:** {m['license']}  ",
    ]
    if manifest.get("doi"):
        lines.append(f"**DOI:** https://doi.org/{manifest['doi']}  ")
    lines += [
        "",
        "## Artifacts",
        "",
        "| File | Size | SHA-256 |",
        "| --- | ---: | --- |",
    ]
    for r in manifest["artifacts"]:
        lines.append(f"| `{r['name']}` | {r['size']} | `{r['sha256']}` |")
    lines += [
        "",
        "## Metadata files",
        "",
        "- `metadata.json` — canonical Misty record",
        "- `zenodo.json` — Zenodo deposit body",
        "- `datacite.json` — DataCite 4.x",
        "- `codemeta.json` — schema.org SoftwareSourceCode",
        "- `CITATION.cff` — CFF 1.2.0",
        "- `manifest.json` — release + reproducibility manifest",
        "",
        "Generated by Misty DOI — Muh Mitha Kijiye!\u2122 (Project ILM).",
    ]
    with open(os.path.join(outdir, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
